apiVersion: v1
kind: Service
metadata:
  name: vitalii-backend
spec:
  selector:
    app: vitalii-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitalii-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vitalii-backend
  template:
    metadata:
      labels:
        app: vitalii-backend
    spec:
      containers:
        - name: app
          image: garber1329/backend-lab5:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
